import { useState, useEffect, useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import Burger from "../components/Burger/Burger.js";
import Menu from "../components/Menu/Menu.js";
import Logo from "../components/Logo/Logo.js";
// import { createClient } from "contentful";
import { ThemeProvider } from "styled-components";
import { GlobalStyles } from "../global";
import { theme } from "../theme.js";
import { useOnClickOutside } from "../hooks.js";
import styles from "../styles/Home.module.css";
import { Test } from "../components/Test.tsx";


// export async function getStaticProps() {
  // const client = createClient({
  //   space: process.env.CONTENTFUL_SPACE_ID,
  //   accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
  // });

  // console.log(client)

  // const data = await client.getEntries();
  // console.log(data.items)
  // return false;

  // return {
  //   props: {
  //     podcasts: data.items.filter(
  //       (item) => item.sys.contentType.sys.id === "podcast"
  //     ),
  //     teamMembers: data.items.filter(
  //       (item) => item.sys.contentType.sys.id === "teamMember"
  //     ),
  //     information: data.items.filter(
  //       (item) => item.sys.contentType.sys.id === "information"
  //     ),
  //     seo: data.items.filter((item) => item.sys.contentType.sys.id === "seo"),
  //     contactInfo: data.items.filter(
  //       (item) => item.sys.contentType.sys.id === "contact"
  //     ),
  //   },
  //   revalidate: 1,
  // };
// }

export default function Home() {
  const [open, setOpen] = useState(false);
  const node = useRef();
  useOnClickOutside(node, () => setOpen(false));

  return (
    <ThemeProvider theme={theme}>
      <>
        <GlobalStyles />
        <div ref={node}>
          <Menu open={open} setOpen={setOpen} />
          <Burger open={open} setOpen={setOpen} />
          <Logo />
        </div>
        <Test />
        {/* <div>
          <h1>Hello. This is burger menu tutorial</h1>
          <img
            src="https://image.flaticon.com/icons/svg/2016/2016012.svg"
            alt="burger icon"
          />
          <small>Icon made by Freepik from www.flaticon.com</small>
        </div> */}
        <div className={styles.container}>
          {/* <Test /> */}
          {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}{" "}
        </div>
      </>
    </ThemeProvider>
  );
}
